import "../app/globals.css";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import AuthProvider from "@/providers/authProvider";
import ReduxProvider from "@/providers/reduxProvider";
export const metadata = {
    title: "T-Shop",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-gray-200">
                <AuthProvider>
                    <ReduxProvider>

                        <Header />

                        {children}

                        <Footer />
                    </ReduxProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
