import "../app/globals.css";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Provider from "@/providers/authProvider";

export const metadata = {
  title: "T-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
   <Provider>
          <Header />
          <>{children}</>
          <Footer />
          </Provider>
      </body>
    </html>
  );
}
