import '../app/globals.css'
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import AuthProvider from '../util/context/AuthProvider';

export const metadata = {
  title: "T-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gray-200'>
        <Header />
        <AuthProvider>{children}</AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
